### ISSUE TITLE
Hello, I'm trying to use your code

### ISSUE THREAD

**Issue by HwangYoungzu** [Prakshal-Jain/React-Video-Editor#1]
After I install with 'npm i react-video-editor' and 'npm install' , I start it. However, if I try to save trimmed video, this kind of error came out. 

TypeError: this.props.saveVideo is not a function

**Comment by Prakshal-Jain** [comment]
Hello HwangYoungzu. Thanks for reaching out.
Yes, saveVideo is a prop you need to pass in the component which will do the post-processing of the video. It will be a function called by the component, and the arguments will be the metadata of the edited video (whether it is muted or not, and what time segments you have cropped.)

You can add this parameter in /src/Video_Editor/VideoEditor.js (see the **render_editor()** function)
Hope this helps. Please follow up if you have any further questions.

**Comment by HwangYoungzu** [comment]
Thank you for your reply.

Actually,  I cannot fully understand your comment.

render_editor = () => {
        return(
            // Props:
            // videoUrl --> URL of uploaded video
            // saveVideo(<metadata of edited video>) --> gives the cut times and if video is muted or not
            
            <Editor videoUrl={this.state.videoUrl}/>
        )
    }

In this code, what I need to change? What will be the modified code..?

**Comment by Prakshal-Jain** [comment]
you can do something like:
`<Editor videoUrl={this.state.videoUrl} saveVideo={this.saveVideo}/>`

And the **saveVideo** function will be like:
`
saveVideo = (metadata) => {
     console.log(metadata)
}
`
metadata have a javascript object consisting of the video edited information. You can do post-processing of the video using this information.

**Comment by Prakshal-Jain** [comment]
I have added the function to the src/Video_Editor/VideoEditor.js
If you would like, you can re-install it again from npm to get the changes.
Thanks!

**Comment by HwangYoungzu** [comment]
Thank you for your comment!
