### ISSUE TITLE
Difference between Editor.js and VideoEditor.js

### ISSUE THREAD

**Issue by LeifAndersen** [Prakshal-Jain/React-Video-Editor#4]
Hey, I'm trying to figure out what the difference between Editor.js and VideoEditor.js is. It looks to me like VideoEditor.js is just a wrapper around Editor.js, but the example project seems to use only Editor.js. Any clarification would be helpful, thanks.

**Comment by LeifAndersen** [comment]
Ahhh, okay, I think I got it. It looks like VideoEditor.js will show the upgrade window if no video is provided, otherwise it will just pass through to Editor.js. I'm going to close this issue now. Thanks.

**Comment by Prakshal-Jain** [comment]
Hello @LeifAndersen 
Glad you figured it out. I have seen your pull request, I will review your code and merge it. Thank you so much for contributing.
Feel free to ask any questions you have.
