### ISSUE TITLE
Is there documentation for this library? Or any guidance on usage for implementing within an existing app? Looks great and would love to use this for my use-case

### ISSUE THREAD

**Issue by Shane-Geary** [Prakshal-Jain/React-Video-Editor#6]

**Comment by Prakshal-Jain** [comment]
Sure, I am working on documentation and building it further. You can expect another release of the next version within 3 weeks.
Sorry, currently my final exams for this semester are going on. As soon as they finish, I will start working :-)

**Comment by Shane-Geary** [comment]
Thank you Prakshal, sounds great and I appreciate it. No worries and good luck on your finals!
